### PR TITLE
let's try to build windows

### LINKED ISSUE #4: make into noarch?
You could try making this a noarch as you have no-arch wheels on pypi anyway

### PR DESCRIPTION
**Pull request by ngam**
fixes #4 

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by pilotchute** [comment]
We may need to read through how numpy is using f2py in their feedstock, since we are also using f2py: https://github.com/conda-forge/numpy-feedstock/tree/main/recipe

in f2py.bat:
```
:: This wrapper script is necessary to make the "f2py" command on windows work

@SET "PYTHON_EXE=%~dp0\..\python.exe"
call "%PYTHON_EXE%" "%~dp0\f2py.py" %*
```

**Comment by ngam** [comment]
> We may need to read through how numpy is using f2py in their feedstock, since we are also using f2py: https://github.com/conda-forge/numpy-feedstock/tree/main/recipe
> 
> in f2py.bat:
> 
> ```
> :: This wrapper script is necessary to make the "f2py" command on windows work
> 
> @SET "PYTHON_EXE=%~dp0\..\python.exe"
> call "%PYTHON_EXE%" "%~dp0\f2py.py" %*
> ```

Good point, let's try their setup

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
Closing because I don't know if this will be actually useful to anyone...

**Pull request closed without merging**
