### PR TITLE
windows support build

### PR DESCRIPTION
**Pull request by marodrig**
This PR tries to use conda-forge to build a win64 compatible version of geocat-f2py by following the example from https://github.com/conda-forge/geocat-f2py-feedstock/pull/16

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by marodrig** [comment]
@conda-forge-admin, please rerender

**Comment by marodrig** [comment]
@conda-forge-admin, please rerender

**Comment by marodrig** [comment]
@conda-forge-admin, please rerender

**Review by erogluorhan — APPROVED** [review]
I am taking this work on from @marodrig.  Let us merge this as is to the feature branch `win-support`, then I can fork that into my personal repo and move the work forward from there.

**Pull request merged**
